version: "3.9"
services:
 #MongoDB services
 mongo_db:
  container_name: db_container
  image: mongo:latest
  restart: always
  volumes:
   - mongo_db:/data/db
   #server services
 server:
  build: .
  container_name: server
  ports:
   - '5000:5000'
  environment:
   PORT: 5000
   MONGODB_URL: mongodb+srv://LanTo:LanTo123456789@cluster0.9r4clsw.mongodb.net/coffemanage?retryWrites=true&w=majority
  volumes:
   - .:/app
  depends_on:
    - mongo_db 
  restart: always
volumes:
 mongo_db: {}
networks: 
  findroom-network:
    driver: bridge
