FROM node:alpine

WORKDIR /app2
# install application dependencies
COPY package.json .
COPY package-lock.json .

RUN npm install -g npm@8.13.2
# add app
COPY . .

EXPOSE 3000
# start app
CMD ["npm","start"]

 